# Generated by Django 4.0.1 on 2022-01-30 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=25, unique=True, verbose_name='username')),
                ('account_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='account id')),
                ('access_token', models.CharField(max_length=40, verbose_name='Токен доступа к данным игрока')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения токена!')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
    ]
