# Generated by Django 4.0.2 on 2022-03-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_captain'),
        ('player', '0002_player_clan_alter_player_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='company.company'),
        ),
    ]
