# Generated by Django 4.0.1 on 2022-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('clan_name', models.CharField(max_length=256, verbose_name='Навание клана')),
                ('clan_tag', models.CharField(max_length=5, unique=True, verbose_name='Тэг клана')),
                ('clan_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID в БД wargaming')),
            ],
        ),
    ]
