# Generated by Django 4.0.2 on 2022-03-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_clan_alter_player_account_id_and_more'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='player.player'),
        ),
    ]
