# Generated by Django 3.1.1 on 2020-12-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanks',
            old_name='name',
            new_name='full_name',
        ),
    ]
