# Generated by Django 3.1.1 on 2020-12-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20201207_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanks',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
